services:
  - type: web
    name: gsheet-push-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python gsheet_push.py"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: gsheet-426913-6e02a0c69199.json

